services:
  nat:
    hostname: nat
    build: ./nat
    container_name: nat
    cap_add: ["NET_ADMIN"]
    restart: always
    networks:
      uplink:
      nat:
        ipv4_address: 192.168.90.254
    volumes:
      - ./nat/iptables.rules:/etc/iptables/rules.v4:ro
    extra_hosts: ["host.docker.internal:host-gateway"]
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:1832:1832"

  fw:
    hostname: fw
    depends_on:
      - nat
    build: ./fw
    container_name: fw
    privileged: true
    cap_add: ["NET_ADMIN"]
    restart: always
    sysctls:
      net.ipv4.ip_forward: 1
    networks:
      nat:
        ipv4_address: 192.168.90.2
      servers:
        ipv4_address: 192.168.50.254
    volumes:
      - ./fw/nftables.conf:/etc/nftables.conf:rw
      # Из-за flush ruleset ломается внутренний DNS-сервис 127.0.0.11 контейнера, поэтому надо вручную назначить корпоративный DNS-сервер
      - ./fw/etc/resolv.conf:/etc/resolv.conf:ro
      - ./ansible.sh:/usr/local/bin/ansible.sh:rw
    env_file:
      - .env
    environment:
      - ANSIBLE_HASH

  srv_dns:
    hostname: srv_dns
    depends_on: [fw]
    build: ./srv_dns
    container_name: srv_dns
    cap_add: ["NET_ADMIN"]
    restart: always
    networks:
      servers:
        ipv4_address: 192.168.50.70
    volumes:
      - ./srv_dns/Corefile:/etc/coredns/Corefile:ro
      - ./srv_dns/investpro.local.db:/etc/coredns/investpro.local.db:ro
      - ./ansible.sh:/usr/local/bin/ansible.sh:rw
    env_file:
      - .env
    environment:
      - GATEWAY_IP
      - ANSIBLE_HASH
    expose:
      - "53"
      - "53/udp"

  srv_web:
    hostname: srv_web
    depends_on: [fw]
    image: alpine:3.20
    container_name: srv_web
    cap_add: ["NET_ADMIN"]
    restart: always
    networks:
      servers:
        ipv4_address: 192.168.50.10
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./srv_web/entrypoint.sh:/entrypoint.sh:ro
      - ./srv_web/log.conf:/etc/nginx/http.d/zz-server.conf:rw
      - ./srv_web/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./srv_web/log.txt:/log.txt:ro
      - ./ansible.sh:/usr/local/bin/ansible.sh:rw
    command: >
      sh -c "exec /bin/sh /entrypoint.sh"
    env_file:
      - .env
    environment:
      - GATEWAY_IP
      - ANSIBLE_HASH
      - USER_HASH
    dns: [192.168.50.70]

  srv_fs:
    hostname: srv_fs
    depends_on: [fw]
    build: ./srv_fs
    container_name: srv_fs
    cap_add: ["NET_ADMIN"]
    restart: always
    # user: root
    networks:
      servers:
        ipv4_address: 192.168.50.30
    volumes:
      - ./samba/share:/share
      - ./ansible.sh:/usr/local/bin/ansible.sh:rw
      - ./srv_fs/etc/samba/smb.conf:/etc/samba/smb.conf:rw
    env_file:
      - .env
    environment:
      - ANSIBLE_HASH
      - SAMBA_USER
      - SAMBA_PASSWORD
      - SAMBA_SHARE_NAME
      - GATEWAY_IP
    dns: [192.168.50.70]

  srv_mail:
    depends_on: [fw]
    build: ./srv_mail
    container_name: srv_mail
    hostname: srv_mail
    domainname: investpro.local
    shm_size: "256m"
    restart: always
    cap_add: ["NET_ADMIN"]
    networks:
      servers:
        ipv4_address: 192.168.50.20
    # no host port publishing; access via fw DNAT1832
    env_file:
      - .env
    environment:
      # hostname/FQDN
      - DMS_HELO_NAME=mail.investpro.local
      # enable core filtering stack
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_POSTSCREEN=0
      - POSTSCREEN_ACTION=ignore
      - ENABLE_DNSBL=0
      - PERMIT_DOCKER=connected-networks
      # DKIM auto-generation for investpro.local
      - ENABLE_OPENDKIM=1
      - DKIM_AUTOGENERATE=1
      - DKIM_SELECTOR=mail
      # IMAP/POP internal only (no host port publishing)
      - ENABLE_IMAP=1
      - ENABLE_POP3=1
      # disable TLS (lab only) see postfix/dovecot overrides in config
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/docker-mailserver/ssl/cert.pem
      - SSL_KEY_PATH=/tmp/docker-mailserver/ssl/key.pem
      # envs
      - ANSIBLE_HASH
      - RSPAMD_PASSWORD
      - GATEWAY_IP
    volumes:
      - ./srv_mail/config/:/tmp/docker-mailserver/
      - ./ansible.sh:/usr/local/bin/ansible.sh:rw
    dns: [192.168.50.70]

networks:
  uplink:
    name: uplink
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.name: br-uplink
  nat:
    driver: bridge
    name: nat
    ipam:
      config:
        - subnet: 192.168.90.0/24
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.name: br-nat

  servers:
    driver: bridge
    name: servers
    ipam:
      config:
        - subnet: 192.168.50.0/24
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.name: br-servers
